"""Init

Revision ID: 2ae1ff3f3f82
Revises: 
Create Date: 2023-01-22 18:05:50.198904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2ae1ff3f3f82"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ongoing_table", sa.Column("marker", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ongoing_table", "marker")
    # ### end Alembic commands ###
